version: "3.8"

services:
  backend:
    depends_on:
      - database
    build: ./
    ports:
      - 3372:3372
    command: ./docker-entrypoint.sh

  database:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: "Kenji@123"
    ports:
      - 3306:3306
    volumes:
      - escola_natacao:/var/lib/mysql/

volumes:
  escola_natacao:
